import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'src');
const distDir = path.join(root, 'dist');
const outFile = path.join(distDir, 'app.jsx');
const indexFile = path.join(root, 'index.html');

fs.mkdirSync(distDir, { recursive: true });

const files = fs
  .readdirSync(srcDir)
  .filter((file) => file.endsWith('.jsx'))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const banner = [
  '/*',
  ' * Generated by scripts/build.mjs from src/*.jsx.',
  ' * Edit the files in src/, then run: node scripts/build.mjs',
  ' */',
  '',
].join('\n');

const body = files
  .map((file) => {
    const content = fs.readFileSync(path.join(srcDir, file), 'utf8').trim();
    return `// ---- ${file} ----\n${content}\n`;
  })
  .join('\n');

const appSource = `${banner}${body}`;
fs.writeFileSync(outFile, appSource, 'utf8');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>IELTS Writing Lab</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.23.2/babel.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Geist:wght@300;400;500;600&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="./styles.css">
</head>
<body>
<div id="root"></div>
<script type="text/babel" data-presets="env,react">
${appSource.replaceAll('</script>', '<\\/script>')}
</script>
</body>
</html>
`;

fs.writeFileSync(indexFile, html, 'utf8');
console.log(`Built ${path.relative(root, outFile)} and direct-open ${path.relative(root, indexFile)} from ${files.length} source files.`);
